### PR TITLE
Add DOI category

### PR DESCRIPTION
**Pull request by chartgerink**
This PR adds the new `DOI` category and adds one post by @Bisaloo to it. 

After merging, I can go ahead and send the feed https://epiverse-trace.github.io/blog-doi.xml to Rogue Scholar for indexing 👍 

This is step 1 for closing #113 - automatically adding the DOIs to the posts will come in a future PR.

### CODE REVIEW

**Comment by Bisaloo** [comment]
Potential concern of doing this as a two-steps workflow:

- we publish the post and broadcast it via the DOI feed
- Rogue Scholar picks it up and gives us a DOI
- we merge a PR to add the DOI

How to make sure it's not accidentally identified as a new post since the hash fingerprint will have changed? 

IDK it's that's a valid concern. I'm not completely sure how RSS & Rogue Scholar work. I remember receiving duplicated RSS notifications in the past because of minor updates of content.

**Comment by chartgerink** [comment]
Thanks for sharing your concern @Bisaloo 🙏 

I have not experienced duplicates in Quarto RSS personally, and I looked into how the feed is constructed to see whether this issue will pop up. 

As it looks, the individual posts in the feed do not contain a hash ID of any kind. This would mean, I suspect, that the feed construction stays the same. The only difference might be the `lastBuildDate` for the feed itself, but that gets updated at every feed regeneration. 

Rogue Scholar did not mention any quirks regarding Quarto and RSS feeds in my emails with them, and they have some experience running this for Quarto blogs ([12 at this time](https://rogue-scholar.org/blogs?page=1&query=&category=&generator=Quarto)). 

We can probably rely on their expertise to smooth this out further if issues arise. In any case, I'll keep an eye on issues that may arise and document + resolve them as is appropriate.

**Review by Bisaloo — APPROVED** [review]

**Comment by noamross** [comment]
Came here because I saw the DOI on your latest post! We build our site nightly, so when we first post there's no DOI but the on the next nightly build we fetch the DOI and include it in the page.  Alternatively you could use JS to fetch the DOI client-side and it would be available quicker. 

It's @maelle's work of course: https://github.com/ropensci/roweb3/pull/632

**Comment by maelle** [comment]
Maybe something to be done in a post-render script? https://quarto.org/docs/projects/scripts.html#pre-and-post-render

**Pull request merged**
