### PR TITLE
Update people to remove avatar for @TimTaylor

### PR DESCRIPTION
**Pull request by chartgerink**
As requested in #333.

### CODE REVIEW

**Comment by Bisaloo** [comment]
Could the image be replaced by a default image? Like a blank or placeholder image? Or would this be confusing?

It would allow us to keep the same structure for contributors with and without avatar.

**Comment by chartgerink** [comment]
I can do this too if you want – I did it this way as it would be the quickest way to fulfill the request.

**Comment by Bisaloo** [comment]
@TimTaylor, would a blank avatar address your request in an appropriate manner?

**Review by Bisaloo — APPROVED** [review]
Thanks!

**Pull request merged**
