### PR TITLE
Add gif with examples of applications

### PR DESCRIPTION
**Pull request by adamkucharski**
This is a straight swap of the `render1717079674378.gif` file to display some applied visual examples of Epiverse tools, which will address issue #292. Will also hopefully be more mobile friendly.

This is V1, so can be further iterated in future when we have additional examples/packages ready and feedback on most commonly used features.

### CODE REVIEW

**Comment by jamesmbaazam** [comment]
I really like the idea but I feel like it might be misleading? It seems to suggest if a user calls the package, they'll immediately get that result.

Maybe, instead of `library(<package>)`, we can just flash the name/logo of the package and flash the plot or printed output. What do you think?

**Review by jamesmbaazam — COMMENTED** [review]
I really like the idea but I feel like it might be misleading? It seems to suggest if a user calls the package, they'll immediately get that result.

Maybe, instead of library(<package>), we can just flash the name/logo of the package and flash the plot or printed output. What do you think?

**Comment by adamkucharski** [comment]
I did try with package logos, but it meant there's quite a lot of visual elements for user to process (and wouldn't work well on mobile). Instead, thought the `library` call hints at these being R packages in a broad way (as reckoned unlikely that a visitor, at least one who works on analysis, would assume that the basic `library()` call could do all that plotting).

Although could definitely use some refinement. Perhaps something like below, that introduces package with text?

epiverse_animation3

(Maybe with a tweak to make the normal font text a slightly different shade)

**Comment by jamesmbaazam** [comment]
> I did try with package logos, but it meant there's quite a lot of visual elements for user to process (and wouldn't work well on mobile). Instead, thought the `library` call hints at these being R packages in a broad way (as reckoned unlikely that a visitor, at least one who works on analysis, would assume that the basic `library()` call could do all that plotting).
> 
> Although could definitely use some refinement. Perhaps something like below, that introduces package with text?
> 
> epiverse_animation3 [ epiverse_animation3 ](https://private-user-images.githubusercontent.com/8329046/345145600-17ae5426-6b91-4900-b2c6-7778b0ea1ea0.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMDI3OTksIm5iZiI6MTcyMDEwMjQ5OSwicGF0aCI6Ii84MzI5MDQ2LzM0NTE0NTYwMC0xN2FlNTQyNi02YjkxLTQ5MDAtYjJjNi03Nzc4YjBlYTFlYTAuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDRUMTQxNDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTAzNDNjOGFjYTkwYzQ3ZTQ2MGUwZGQ1NWQxOWRkMjk0MjY0NmJjOWQ3ZmM0YThiZWFmOTI4MzFmYWQ4YTQzYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qAKZPeVq4pquczYyPsiFDE0Kq9uBoSHyemSHKSe6Pvg) [ ](https://private-user-images.githubusercontent.com/8329046/345145600-17ae5426-6b91-4900-b2c6-7778b0ea1ea0.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxMDI3OTksIm5iZiI6MTcyMDEwMjQ5OSwicGF0aCI6Ii84MzI5MDQ2LzM0NTE0NTYwMC0xN2FlNTQyNi02YjkxLTQ5MDAtYjJjNi03Nzc4YjBlYTFlYTAuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDRUMTQxNDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTAzNDNjOGFjYTkwYzQ3ZTQ2MGUwZGQ1NWQxOWRkMjk0MjY0NmJjOWQ3ZmM0YThiZWFmOTI4MzFmYWQ4YTQzYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.qAKZPeVq4pquczYyPsiFDE0Kq9uBoSHyemSHKSe6Pvg)
> 
> (Maybe with a tweak to make the normal font text a slightly different shade)

I love the new one you're suggesting 🤩 .

**Comment by adamkucharski** [comment]
Thanks! I've pushed a new version with different colour for package name – I tried highlighting key words, but struggled to make it consistent. I also added some other packages, as thought nice opportunity to showcase. Preview here:

render1717079674378

Will merge on Monday if no major edits – can always refine/iterate further in future versions!

**Review by jamesmbaazam — APPROVED** [review]
It looks good to me.

**Review by Bisaloo — APPROVED** [review]
I received validation for this internally as well, with the caveat that potentially more appropriate visual materials are in the pipeline.

Before merging, could you please update the alt-text and possibly the dimensions (the text looks almost comically large compared to the rest of the page) here:

https://github.com/epiverse-trace/epiverse-trace.github.io/blob/08330689f1bf169b8f762d75fd2e549a06f74d03/_components/Hero.jsx#L50-L52

?

Thanks!

When Chris is back, we should also ask them to have a look since they are the expert who created this page.

**Comment by adamkucharski** [comment]
Thanks all. I've updated the alt-text and merged – I didn't edit dimensions as looked like width was aligned with a wider template, so didn't want to inadventenly introduce instabilities.

**Pull request merged**
